[env]
CARAPACE_BRIDGES = "zsh"
HOMEBREW_BUNDLE_FILE_GLOBAL = "{{env.XDG_CONFIG_HOME}}/homebrew/Brewfile"
HOMEBREW_NO_ANALYTICS = true
HOMEBREW_NO_UPDATE_REPORT_NEW = true
MCFLY_DELETE_WITHOUT_CONFIRM = true
MCFLY_DISABLE_MENU = true
MCFLY_INTERFACE_VIEW = "BOTTOM"
MCFLY_RESULTS_SORT = "LAST_RUN"
NODE_COMPILE_CACHE = "{{env.XDG_CACHE_HOME}}/node/compile"
RIPGREP_CONFIG_PATH = "{{env.XDG_CONFIG_HOME}}/ripgrep/.ripgreprc"

[settings]
activate_aggressive = true
always_keep_download = false
always_keep_install = false
disable_default_registry = true
experimental = true
idiomatic_version_file_enable_tools = []
paranoid = true
status.missing_tools = "always"

[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:a8m/envsubst" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:cantino/mcfly" = "latest"
"aqua:git-lfs/git-lfs" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:mvdan/sh" = { version = "latest", exe = "shfmt" }
"aqua:nametake/golangci-lint-langserver" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:reteps/dockerfmt" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sigstore/cosign" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:zellij-org/zellij" = "latest"
"cargo:lumen" = "latest"
"github:neovim/neovim" = { version = "nightly", extract_all = "true", bin_path = "bin" }
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.64.8"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@angular/language-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:npm-check-updates" = "latest"
"npm:opencode-ai" = "latest"
"npm:opencommit" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"vfox:version-fox/vfox-cmake" = "latest"
bun = "latest"
fzf = "latest"
go = "latest"
node = "22"
rust = "latest"
shellcheck = "latest"
yarn = "latest"

[tasks.up]
description = "Upgrade all the things"
run = [
  "brew cleanup --prune=all",
  "brew bundle --global",
  "mise prune --yes",
  "mise upgrade",
  "rm -rf \"$XDG_CONFIG_HOME/yazi/plugins\"",
  "ya pkg upgrade",
  "nvim --headless +\"lua vim.pack.update(nil, { force = true })\" +qa",
]
